katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from todolist.views import finish_task, show_todolist, register, login_user, logout_user, show_create_task, create_task, delete_task, show_todolist_json, add_json_task, delete_json_task

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', show_create_task, name='show-create-task'),
    path('add-task/', create_task, name='create-task'),
    path('delete-task/<int:i>/', delete_task, name='delete-todo'), 
    path('finish-task/<int:i>/', finish_task, name='finish-task'),
    path('json/', show_todolist_json, name="show_todolist_json"),
    path('add/', add_json_task, name="add_json_task"),
    path('delete/<int:id>/', delete_json_task, name='delete_json_task'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todolist/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    date = models.CharField(max_length=225)
    title = models.CharField(max_length=225)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)
    finish = models.CharField(max_length=225, default='not finished')

todolist/views.py
import http
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.urls import reverse
from todolist.models import ToDoList

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todolist_items = ToDoList.objects.filter(user=request.user)

    for i in range(len(todolist_items)) :
        if (todolist_items[i].is_finished == True) :
            todolist_items[i].finish = "Finished"
        elif (todolist_items[i].is_finished == False):
            todolist_items[i].finish = "Not finished"
    context = {
        'todolist': todolist_items,
    }
    return render(request, 'todolist.html', context)

@login_required(login_url="/todolist/login")
def show_create_task(request):
    return render(request, 'create-task.html')

@login_required(login_url="/todolist/login")
def create_task(request):
    if request.method == "POST":
        x = request.POST.get('title')
        y = request.POST.get('description')
        new_item = ToDoList.objects.create(user=request.user, date = str(datetime.datetime.now().date()), title= x, description = y)
        new_item.save()
        return HttpResponseRedirect('/todolist/')

@login_required(login_url="/todolist/login")
def finish_task(request, i):
    obj = get_object_or_404(ToDoList, id=i)
    if request.method == 'POST':
        obj.is_finished = not obj.is_finished
        obj.save()
        return redirect('/todolist/')

    return render(request, 'todolist.html', {'obj' : obj})

@login_required(login_url="/todolist/login")
def delete_task(request, i):
    y = ToDoList.objects.get(id= i)
    y.delete()
    return HttpResponseRedirect('/todolist/') 

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url="/todolist/login")
def show_todolist_json(request):
    tasks = ToDoList.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', tasks), content_type='application/json')

@login_required(login_url="/todolist/login")
def add_json_task(request):
    if request.method == "POST":
        x = request.POST.get('title')
        y = request.POST.get('description')
        new_item = ToDoList.objects.create(user=request.user, date = str(datetime.datetime.now().date()), title= x, description = y)
        new_item.save()
    return HttpResponse('')

@login_required(login_url="/todolist/login")
def delete_json_task(request, id):
    user = request.user
    task = ToDoList.objects.get(pk=id)

    if user.id == task.user_id and request.method == 'DELETE':
        task.delete()
        
    return HttpResponse('')

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create New Task</title>
{% endblock meta %}

{% block content %}

<!-- <style>
    form  { 
        display: flex;   
        justify-content: center;
        align-items: center;   
        gap: 10px;
        margin: auto;
        margin-top: 50px;
    }

    .btn-submit {
        display: flex;
        margin-left: auto;
        margin-top: 20px;
        letter-spacing: .02em;
    }
    
    p     { display: table-row;  }
    label { display: table-cell; }
    input { display: table-cell; margin-top: 20px; margin-left: 10px;}
    textarea { display: table-cell; margin-left: 10px; margin-top: 10px;}

</style> -->

<!-- <form  class="form-create-task" action="/todolist/add-task/" method = "POST">
    {% csrf_token %}
    <fieldset>
        <p>
            <label class="description-label">Title: </label>
            <input type="text" name="title" required>
        </p>
        <p>
            <label display>Description: </label>
            <textarea name="description" class="description-input" cols="25" rows="10" required></textarea>
        </p>
        <input class="btn-submit" type="submit" value="Add Todo Item">
    </fieldset>
</form>  -->

<section class="vh-100" style="background-color: #15aabf;">
    <div class="container-fluid py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-9 col-md-7 col-lg-5 col-lg-6 col-xl-3">
                <div class="card bg-light text-black d-flex justify-content-center" style="border-radius: 1rem; padding: 20px; height: 450px;">
                    <h2 class="d-flex justify-content-center" style="margin-bottom: 1rem;">Create New Task</h2>
                
                    <form class="form-create-task" action="/todolist/add-task/" method = "POST">
                        {% csrf_token %}
                        <div class="form-outline mb-4">
                            <label class="form-label" for="title-task">Title</label> 
                            <input type="text" id="title-task" name="title" class="form-control" required>
                        
                        </div>
                
                        <div class="form-outline mb-4">
                            <label class="form-label" for="description-task">Description</label> 
                            <textarea name="description" cols="10" rows="5"  class="form-control" required></textarea>
                            
                        </div>
                
                        <div class="row d-flex justify-content-center align-content-center">
                            <input class="btn btn-primary btn-block mb-4" style="width: 50%; margin-top: 1rem" type="submit" value="Add task">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<section class="vh-100" style="background-color: #15aabf;">
    <div class="container-fluid py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-9 col-md-7 col-lg-5 col-lg-6 col-xl-3">
                <div class="card bg-light text-black d-flex justify-content-center" style="border-radius: 1rem; padding: 20px; height: 450px;">
                    <h2 class="d-flex justify-content-center">Login</h2>
                
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-outline mb-4">
                            <label class="form-label" for="username-login-form">Username</label> 
                            <input type="text" id="username-login-form" name="username" placeholder="Enter Your Username Here" class="form-control">
                        
                        </div>
                
                        <div class="form-outline mb-4">
                            <label class="form-label" for="password-login-form">Password</label> 
                            <input type="password" id="password-login-form" name="password" placeholder="Enter Your Password Here" class="form-control">
                        
                        </div>
                
                        <div class="row d-flex justify-content-center align-content-center">
                            <input class="btn btn-primary btn-block mb-4" style="width: 50%;" type="submit" value="Login">
                        </div>
                    </form>
                
                    <div class="d-flex justify-content-center align-content-center" style="height: 50px;">
                        {% if messages %}
                            {% for message in messages %}
                            <p>{{ message }}</p>
                            {% endfor %}
                        {% endif %}     
                    </div>
                        
                    <div class="d-flex justify-content-center align-content-center">
                        <p class="mb-0"> Belum mempunyai akun? <a href="{% url 'todolist:register' %}" style="text-decoration: none;">Buat Akun</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<section class="vh-100" style="background-color: #15aabf;">
    <div class="container-fluid py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-10 col-md-8 col-lg-6 col-xl-4">
                <div class="card bg-light text-black d-flex justify-content-center" style="border-radius: 1rem; padding: 20px;">
                    <h2 class="d-flex justify-content-center">Formulir Registrasi</h2>
                
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-outline mb-4">
                            <label class="form-label" for="id_username">Username</label> 
                            <input type="text" id="id_username" maxlength="150" name="username" placeholder="150 characters or fewer. Letters, digits and @/./+/-/_ only" class="form-control" required>
                            <!-- <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span> -->
                        </div>
                
                        <div class="form-outline mb-4">
                            <label class="form-label" for="id_password1">Password</label> 
                            
                            <input type="password" id="id_password1" name="password1" placeholder="Enter Password" class="form-control" autocomplete="new-password" required>
                            <p style="font-size: 12px; margin-bottom: 0;">Your password can’t be too similar to your other personal information.</p>
                            <p style="font-size: 12px; margin-bottom: 0;">Your password must contain at least 8 characters.</p>
                            <p style="font-size: 12px; margin-bottom: 0;">Your password can’t be a commonly used password.</p>
                            <p style="font-size: 12px; margin-bottom: 0;">Your password can’t be entirely numeric.</p>
                        </div>

                        <div class="form-outline mb-4" >
                            <label class="form-label" for="id_password2">Password Confirmation</label> 
                            <input type="password" id="id_password2" name="password2" placeholder="Enter the same password as before, for verification" class="form-control" autocomplete="new-password" required>                        </div>
                
                        <div class="row d-flex justify-content-center align-content-center">
                            <input class="btn btn-primary btn-block" style="width: 40%; margin-top: 1.5rem; margin-bottom: 0;" type="submit" name="submit" value="Daftar">
                        </div>
                    </form>
                
                    <div class="d-flex justify-content-center align-content-center">
                        {% if messages %}  
                            <ul>   
                                {% for message in messages %}  
                                    <li>{{ message }}</li>  
                                    {% endfor %}  
                            </ul>   
                        {% endif %} 
                    </div>
                        

                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>To Do List</title>
<link rel="stylesheet" href="{% static 'todolist.css' %}">
{% endblock meta %}

{% block content %}
<div>
  <nav class="nav-top-content">
      <div></div>
      <div class="title">
        <h1>TO DO LIST</h1>
      </div>
      <div class="nav-btn-logout">
        <input class="btn-logout" type="button" value="Logout", onclick="window.location='/todolist/logout/';"/>
      </div>
  </nav>
  
  <div class="identity"><h6>{{user.get_username}}'s todolist</h6></div>

  <input class="btn-create-task" data-bs-toggle="modal" data-bs-target="#exampleModal" type="button" value="+"/>
    
  <div class="section-cards">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="content container-content"></div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <form method="POST">
    {% csrf_token %}
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Create New Task</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="form-outline mb-4">
            <label class="form-label" for="title-task">Title</label> 
            <input type="text" id="title-task" name="title" class="form-control" required>
        </div>
  
        <div class="form-outline mb-4">
            <label class="form-label" for="description-task">Description</label> 
            <textarea name="description" cols="10" rows="5" id="description-task" class="form-control" required></textarea>
        </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="add-task-btn btn btn-primary" data-bs-dismiss="modal">Add task</button>
        </div>
      </div>
    </div>
  </form>
</div>
  
  <script>
    function showTask() {
      $.get('/todolist/json/', function(data, status){
      let content = '';
      for (let i=0; i<data.length; i++){
        let finish = data[i].fields.is_finished ? 'Finished':'Not Finished';
        content += `
        <div class="cards-box">
            <div class="cards">
              <div class="hover_color_bubble"></div>
              <div class="title">
                <h3>${data[i].fields.title}</h3>
                <h6>${data[i].fields.date}</h6>
                <h6>${finish}</h6>
              </div>
              <div class="description">
                <p>
                  ${data[i].fields.description}
                </p>
                <form action="/todolist/finish-task/${data[i].pk}/" method = "POST">{% csrf_token %}
                  <button type="submit" class="finish-task">Finish Task</button>
                </form> 
                </div>
                <button onclick="deleteTask(${data[i].pk})" class="delete-task">Delete Task</button>
            </div>
          </div>
        `;
        $('.content').html(content);
      }
    })
    }
    
    function deleteTask(id) {
      $.ajax({
            type: 'DELETE',
            url: `/todolist/delete/${id}/`,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
            },
            success: function(data) {
                $.get("/todolist/json/", showTask);
            },
        });
    }
    
    $(document).ready( function(){
      $.get("/todolist/json/", showTask);

      $('.add-task-btn').click( function(){
        let title = $('#title-task').val();
        let description = $('#description-task').val();
        let CSRFtoken = $('input[name="csrfmiddlewaretoken"]').val();
        $.post('/todolist/add/', {
          title: title,
          description: description,
          csrfmiddlewaretoken: CSRFtoken
        }, $.get("/todolist/json/", showTask))
        
      })
    })
  </script>
{% endblock content %}